name: PocketRPG
main: PocketRPG\main
version: 0.0.9
api: [2.0.0]
author: Sandertv

commands:
  startquest:
    description: "Start a quest"
    usage: "/startquest <number>"
  listquest:
    description: "Gives a list of quests"
    usage: "/listquest <number>"
  seequest:
    description: "See a currently opened quest"
    usage: "/seequest <number>"
  endquest:
    description: "Finish a quest"
    usage: "/endquest <number>"
  rpgstart:
    description: "Start your adventure"
    usage: "/rpgstart <class>"
  partycreate:
    description: "Create a party"
    usage: "/partycreate <partyname>"
  partyinvite:
    description: "Invite someone to your party"
    usage: "/partyinvite <playername> <partyname>"
  partyleave:
    description: "Start your adventure"
    usage: "/partyleave <partyname>"
