---
name: PocketRPG
main: PocketRPG\main
version: 0.0.9
api: [2.0.0]
author: Sandertv

commands:
  startquest:
    description: "Start a quest"
  listquest:
    description: "Gives a list of quests"
  seequest:
    description: "See a currently opened quest"
  endquest:
    description: "Finish a quest"
  rpgstart:
    description: "Start your adventure"
  partycreate:
    description: "Create a party"
  partyinvite:
    description: "Invite someone to your party"
  partyleave:
    description: "Start your adventure"
...
